version: "3.11"

services:
  lms_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms_genai_app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    restart: always
